@include('frontend.includes.head')
@include('frontend.includes.header')
@include('frontend.includes.download')
@include('frontend.includes.features')
@include('frontend.includes.about')
@include('frontend.includes.testimonial')
@include('frontend.includes.contact')
@include('frontend.includes.footer')