@include('frontend.includes.english.head')
@include('frontend.includes.english.header')
@include('frontend.includes.english.download')
@include('frontend.includes.english.features')
@include('frontend.includes.english.about')
@include('frontend.includes.english.testimonial')
@include('frontend.includes.english.contact')
@include('frontend.includes.english.footer')    
